x="Hello World "
print(type(x))
x=20
print(type(x))
x=20.5
print(type(x))
x=5j
print(type(x))
x=["apple","banana","cherry"]
print(type(x))
x=("apple","banana","cherry")
print(type(x))
x=range(5)
print(type(x))
x={"name":"john","age":36}
print(type(x))
x={"apple","banana","cherry"}
print(type(x))
x=frozenset({"apple","banana","cherry"})
print(type(x))
x=True
print(type(x))
x=b"Hello"
print(type(x))
x=bytearray(5)
print(type(x))
x=memoryview(bytes(5))
print(type(x))
x=None
print(type(x))